export const IPC_CHANNEL = {
  getCharms: 'get-charms',
  selectCharm: 'select-charm',
  toggleWindow: 'toggle-window',
  toggleGallery: 'toggle-gallery',
  setGalleryOpen: 'set-gallery-open',
  triggerRitual: 'trigger-ritual',
  moveWindow: 'move-window',
  setOverlayInteractive: 'set-overlay-interactive',
  getDragBoundary: 'get-drag-boundary',
  setDragBoundary: 'set-drag-boundary',
  getFullDesktopOverlay: 'get-full-desktop-overlay',
  setFullDesktopOverlay: 'set-full-desktop-overlay',
  getCompactOverlaySize: 'get-compact-overlay-size',
  setCompactOverlaySize: 'set-compact-overlay-size',
  toggleUndangle: 'toggle-undangle',
  openSettings: 'open-settings',
  checkUpdates: 'check-updates',
  downloadUpdate: 'download-update',
  installUpdate: 'install-update',
  quitApp: 'quit-app',
} as const;

export const IPC_EVENT = {
  charmsUpdated: 'charms-updated',
  charmSelected: 'charm-selected',
  visibilityUpdated: 'visibility-updated',
  galleryUpdated: 'gallery-updated',
  ritualTriggered: 'ritual-triggered',
  undangleUpdated: 'undangle-updated',
  settingsOpened: 'settings-opened',
  updateStatus: 'update-status',
  galleryTab: 'gallery-tab',
  dragBoundaryUpdated: 'drag-boundary-updated',
  fullDesktopOverlayUpdated: 'full-desktop-overlay-updated',
  compactOverlaySizeUpdated: 'compact-overlay-size-updated',
} as const;
